export let GET_USER_PENDING="GET_USER_PENDING";
export let GET_USER_SUCCESS="GET_USER_SUCCESS";
export let GET_USER_ERROR="GET_USER_ERROR";

export let POST_USER_PENDING="POST_USER_PENDING";
export let POST_USER_SUCCESS="POST_USER_SUCCESS";
export let POST_USER_ERROR="POST_USER_ERROR";

export let DELETE_USER_PENDING="DELETE_USER_PENDING";
export let DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export let DELETE_USER_ERROR="DELETE_USER_ERROR";

